version: "3.0"
services:
  # Databases
  customer_db:
    image: postgres:12-alpine
    container_name: customer-database
    ports:
      - "5434:5432"
    volumes:
      - ./data/customer_db:/var/lib/postgresql/data
      - ./sql/init-customer.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer

  customer:
    image: customer
    container_name: customer-rest
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_HOST: customer_db
      DB_PORT: 5432

  book_db:
    image: postgres:12-alpine
    container_name: book-database
    ports:
      - "5433:5432"
    volumes:
      - ./data/book_db:/var/lib/postgresql/data
      - ./sql/init-book.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book

